// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing/StartAppsStudioFullLandingPage.tsx": () => import("../components/mockups/landing/StartAppsStudioFullLandingPage.tsx"),
  "./components/mockups/landing/StartAppsStudioSplitHeroVariant.tsx": () => import("../components/mockups/landing/StartAppsStudioSplitHeroVariant.tsx")
};
