import { type LocaleEditorialContent } from "../editorial";
import { getPost } from "../posts";

const sourcePost = getPost("the-mvp-brief-is-your-first-product-decision");
if (!sourcePost) throw new Error("Missing MVP editorial source post.");

export const AZ_EDITORIAL_CONTENT: LocaleEditorialContent = {
  copy: {
    journalName: "Jurnal · Cild I", journalTitle: "Studiyadan sahə qeydləri.", journalDescription: "Google-da sıralanan və AI tərəfindən sitat gətirilən MVP-lərin təqdimatı haqqında qeydlər: GEO, vibe-coding və işdə AI-nin vəziyyəti.",
    resourcesTitle: "Əvvəl düzgün şeyi qurun, sonra onu yaxşı qurun.", resourcesDescription: "Məhsul strategiyası, AI dəstəkli hazırlama, texnologiya seçimi, sahiblik, təhvilvermə və MVP-nin istifadəyə verilməsi haqqında praktik resurslar.",
    read: "Qeydi oxu", minutes: "dəq oxu", allNotes: "Bütün qeydlər", sources: "Mənbələr", shortAnswer: "Qısa cavab", language: "Dil",
    translatedArticleTitle: "MVP brifi ilk məhsul qərarınızdır", translatedArticleDescription: "Faydalı MVP brifi ilk istifadəçini adlandırır, birinci versiyanın sərhədini müəyyənləşdirir və növbəti qərar üçün sübutları təyin edir.",
  },
  resources: {
    title: "Əvvəl düzgün şeyi qurun, sonra onu yaxşı qurun.", description: "Məhsul strategiyası, AI dəstəkli hazırlama, texnologiya seçimi, sahiblik, təhvilvermə və MVP-nin istifadəyə verilməsi haqqında praktik resurslar.",
    eyebrow: "Start Apps Studio · Resurslar", primaryAction: "Layihənizi müzakirə edin", journalAction: "Jurnalı oxu",
    routes: { title: "Növbəti marşrutu seçin", intro: "Doğru ilk mərhələ nə qədər proqram təminatı təsəvvür edə bilməyinizdən deyil, nəyisə sübut etməli olduğunuzdan asılıdır.", cards: [
      { kicker: "01 · İstiqamət", title: "Ən kiçik faydalı sübutla başlayın", text: "İstifadəyəvermə saytı insanların təklifi anlayıb-anlamadığını cavablayır. Prototip onların təcrübəyə reaksiya verə bilib-bilmədiyini cavablayır. MVP real istifadəçilərin nə etdiyini cavablayır.", bullets: ["Növbəti buraxılışın açmalı olduğu bir qərarı seçin", "İlk versiyanı ondan öyrənmək üçün kifayət qədər dar saxlayın", "Ehtiyac duyduğunuz sübuta uyğun paketi istifadə edin"] },
      { kicker: "02 · AI dəstəkli hazırlama", title: "Struktur möhkəm olduqda sürət faydalıdır", text: "AI araşdırmanı, kodlaşdırmanı və yoxlamanı sürətləndirə bilər. O, məhsul mühakiməsini, arxitekturanı, testi və ya nəticəyə cavabdeh insanı əvəz etmir.", bullets: ["Seçimləri araşdırmaq və təkrarı azaltmaq üçün AI-dən istifadə edin", "Yaradılmış kodu həqiqi istifadəçi axınlarına qarşı yoxlayın", "Buraxılmış sistemi başa düşülən və genişləndirilə bilən saxlayın"] },
      { kicker: "03 · Sahiblik", title: "Təhvilvermədə nəyin gəldiyini soruşun", text: "Uğurlu hazırlama yalnız yekun təqdimatdan ibarət deyil. Mənbə kodu, dizayn faylları, hesablar, yerləşdirmə girişi və kontekst sizin və ya növbəti komandanız üçün hazır olmalıdır.", bullets: ["Hesabların və işçi faylların kimə məxsus olduğunu təsdiqləyin", "Son həftədən əvvəl işin gedişini nəzərdən keçirin", "Sənədləşdirilmiş, saxlanıla bilən təməl ilə ayrılın"] },
      { kicker: "04 · Tərəfdaş uyğunluğu", title: "İş üsulunu müqayisə edin", text: "Məhsul tərəfdaşı seçməzdən əvvəl əhatə dairəsinin aydınlığını, rəy dövrlərini, məsuliyyəti, istifadəyəvermədən sonrakı dəstəyi və marşrutun biznesinizin mərhələsinə uyğunluğunu müqayisə edin.", bullets: ["Məhsul qərarlarını kim verir?", "Nə vaxt real bir şey görəcəksiniz?", "Başqa komanda sıfırdan başlamadan davam edə bilərmi?"] },
    ] },
    packages: { title: "Paket marşrutlaşdırma bələdçisi", intro: "Söhbət üçün başlanğıc nöqtəsi kimi açıq paketlərdən istifadə edin. İş başlamazdan əvvəl əhatə dairəsi razılaşdırılır.", columns: ["Marşrut", "İnvestisiya", "Tipik müddət", "Sizə lazım olduqda ən uyğundur"], rows: [
      { route: "İstifadəyəvermə saytı", investment: "$2,600", timing: "3–5 iş günü", bestFor: "Təklifi izah etmək və inandırıcı rəqəmsal varlıq yaratmaq" }, { route: "Prototip", investment: "$6,000", timing: "5–10 gün", bestFor: "Yoxlama, investisiya cəlbi və ya ilkin söhbətlər üçün ideyanı hiss edilən etmək" }, { route: "MVP", investment: "$15,000–$30,000", timing: "3–8 həftə", bestFor: "Həqiqi veb, iOS və ya Android məhsulunu istifadəçilərin əlinə vermək" }, { route: "Fərdi", investment: "$25,000", timing: "1–6 ay", bestFor: "Uzunmüddətli məsuliyyətlə daha böyük və ya mürəkkəb sistem qurmaq" },
    ] },
    toolkit: { title: "İşin arxasındakı alətlər", intro: "Alətlər məhsul nəticəsi, onu təhvil alacaq komanda və biznesin mərhələsi üçün seçilir.", groups: [
      { label: "İdeyanız görünən hala gətirilir", description: "Konseptin toxuna, investorlarla paylaşa və real istifadəçilərlə sınaqdan keçirə biləcəyiniz ekranlara çevrilməsi.", tools: [{ name: "Figma", note: "koddan əvvəl hər ekran dizayn edilir", tone: "figma" }, { name: "Rork", note: "bir neçə günə real telefonda sınayın", tone: "rork" }, { name: "Lovable", note: "istifadəyəvermə saytı bir neçə günə canlıdır", tone: "lovable" }, { name: "Replit", note: "işlədə və redaktə edə biləcəyiniz işlək məhsul", tone: "replit" }] },
      { label: "Məhsulunuz uzunömürlü qurulur", description: "İstifadəçilərinizin quraşdırdığı, açdığı və ödəniş etdiyi tətbiqi işlədən mühəndislik.", tools: [{ name: "React Native", note: "bir kod bazası, iOS + Android", tone: "expo" }, { name: "Swift", note: "yerli iOS, iPhone-da ən sürətli", tone: "swift" }, { name: "Kotlin", note: "yerli Android, Play Store-a tam çıxış", tone: "kotlin" }, { name: "Node + PostgreSQL", note: "məlumatlarınız təhlükəsizdir və ixrac sizindir", tone: "node" }] },
      { label: "Gəlir və istifadəəyəvermə, ilk gündən", description: "Ödənişlər, yeniləmələr və kod təhlükəsizliyi sonradan əlavə edilməyib, başlanğıcdan qoşulub.", open: true, tools: [{ name: "Stripe", note: "birdəfəlik ödənişlər, abunəliklər, yüksəltmələr", tone: "stripe" }, { name: "RevenueCat", note: "App Store və Play Store hesablaşması", tone: "revenuecat" }, { name: "GitHub", note: "gündəlik ehtiyat nüsxələr: kodunuz həmişə təhlükəsizdir", tone: "github" }, { name: "Automation", note: "n8n + Make rutin işləri həll edir", tone: "hooks" }] },
      { label: "AI arxa planda, yolunuzda deyil", description: "İnsan istiqamət və keyfiyyət meyarına sahibkən AI araşdırmanı, həyata keçirməni və yoxlamanı dəstəkləyə bilər.", tools: [{ name: "Claude", note: "əsas qurucu və kod yoxlayıcısı", tone: "claude" }, { name: "Gemini", note: "bütün məhsulu bir anda yoxlayır", tone: "gemini" }, { name: "GPT-5", note: "mətnlər, axınlar və yaradıcı istiqamət", tone: "gpt" }, { name: "Llama 4", note: "həssas iş üçün özünüzün yerləşdirdiyi seçim", tone: "llama" }] },
    ], footnote: "Kod, hesablar və işçi fayllar sizdə qalır. Daha yaxşı alət çıxanda məhsulunuzu girov saxlamadan onu əvəz etmək olar." },
    journal: { title: "Jurnaldan sahə qeydləri", text: "MVP strategiyası, SEO, GEO, vibe-coded tətbiqlər və məhsulu buraxmağı asanlaşdıran qərarlar haqqında daha ətraflı qeydlər.", readAction: "Qeydi oxu", minutesLabel: "dəq oxu", allAction: "Bütün jurnal qeydləri", fallbackCategory: "Jurnal", postSlugs: ["base44-vs-lovable-which-one-for-your-next-app", "the-mvp-brief-is-your-first-product-decision", "make-your-brand-visible-in-chatgpt", "vibe-coded-apps-have-an-seo-problem", "backlinks-still-decide-who-gets-recommended", "ai-overviews-citation-playbook-for-mvps"] },
    cta: { title: "Ağlınızda bir marşrut var?", text: "Harada olduğunuzu, nəyi sübut etməli olduğunuzu və hazırda nəyin ilişib qaldığını paylaşın.", action: "Aydın növbəti addım alın" },
  },
  post: { ...sourcePost, title: "MVP brifi ilk məhsul qərarınızdır", seoTitle: "MVP brifləri: ilk məhsul qərarınız | Start Apps Studio", description: "Faydalı MVP brifi sadəcə ideyanı təsvir etmir. O, istifadəçini adlandırır, birinci versiyanın ətrafında dəqiq xətt çəkir və qurmağa davam edib-etməməyinizi bildirən sübutları müəyyənləşdirir.", seoDescription: "MVP brifiniz sənəd işi deyil, məhsul qərarıdır. Dizayn və ya kod başlamazdan əvvəl faydalı brifin müəyyən etməli olduğu üç şeyi öyrənin.", excerpt: "Ən yaxşı MVP brifləri uzun olmur. Onlar məhsulun kim üçün olduğunu, birinci versiyanın nə etməkdən imtina etdiyini və hansı sübutun növbəti həftəlik işi qazandığını həll edir.", category: "Sahə qeydləri", tags: ["MVP", "Məhsul strategiyası", "Təsisçilər", "Əhatə dairəsi"], body: [
    { type: "answer", text: "Faydalı MVP brifi dizayn başlamazdan əvvəl üç qərar verir: məhsulun kim üçün olduğu, birinci versiyanın qəsdən nələri kənarda saxlayacağı və hansı istifadəçi sübutunun növbəti investisiyanı əsaslandıracağı. Buna görə brif sənəd işi deyil. Bu, ilk məhsul qərarıdır." },
    { type: "p", text: "Təsisçilər çox vaxt əslində ideyanın təsviri olan briflə gəlirlər: bazar haqqında bir neçə abzas, funksiya siyahısı və məhsulun nə vaxtsa hara gedə biləcəyi barədə bir cümlə. Söhbətə başlamaq üçün kifayətdir, amma ona qarşı məhsul buraxmaq üçün deyil. Qurucu komandaya ambisiyanı sınaqdan keçirilə bilən seçimlər ardıcıllığına çevirən daha kiçik, daha kəskin sənəd lazımdır." },
    { type: "h2", text: "Faydalı brif üç işi görür", id: "three-jobs" }, { type: "h3", text: "1. Problemi olan şəxsi adlandırır", id: "name-the-user" },
    { type: "p", text: "“Kiçik bizneslər” bir bazardır. Bu, ilk istifadəçi deyil. Yaxşı brif şəxsi, onun içində olduğu anı və bu gün istifadə etdiyi dolayı yolu adlandırır. Sabahkı ləğvləri doldurmağa çalışan klinika menecerinin problemi, hər ikisi səhiyyəyə aid olsa da, yeni görüş axtaran pasiyentin problemindən fərqlidir. İlk istifadəçi nə qədər konkret olsa, məhsulun sonra nə etməli olduğuna qərar vermək bir o qədər asanlaşır." },
    { type: "h3", text: "2. Birinci versiyanın ətrafında xətt çəkir", id: "draw-the-line" }, { type: "p", text: "Funksiya siyahısı nəyin təsəvvür edildiyini deyir. Əhatə dairəsi xətti nəyin qurulacağını deyir. Əsas dövrəni bir cümlə ilə yazın, sonra həmin dövrəni etibarlı edən işi sadalayın: əsas ekranı, bir mənalı əməliyyatı, arxasındakı məlumatları və istifadəçiyə onun işlədiyini bildirən rəyi. Qalan hər şey sonrakı üçün namizəddir, istifadəyəvermə üçün səssiz tələb deyil." },
    { type: "h3", text: "3. Növbəti sübutu müəyyənləşdirir", id: "define-the-proof" }, { type: "p", text: "“Buraxaq və nə olacağını görək” öyrənmə planı deyil. İlk bir neçə həftədə nəyi müşahidə etməyi gözlədiyinizə qərar verin: tamamlanmış iş axını, təkrarlanan əməliyyat, ödənişli dönüşüm və ya müəyyən istifadəçi tipi ilə təsisçi müsahibəsi. Ölçü mürəkkəb olmalı deyil. O, növbəti məhsul qərarını dəyişə bilməsi üçün istifadəçi davranışına kifayət qədər yaxın olmalıdır." },
    { type: "h2", text: "Ekrandan əvvəl nəyi yazmaq lazımdır", id: "before-a-screen" }, { type: "ul", items: ["İlk istifadəçi: bir rol, bir vəziyyət və bir ağrılı dolayı yol", "Əsas dövrə: dəyər yaradan və təkrar baş verə bilən ən kiçik əməliyyat", "İstifadəyəvermə sərhədi: birinci versiya üçün açıq şəkildə əhatə dairəsindən kənar olanlar", "Etibar tələbi: istifadəçi hərəkət etməzdən əvvəl nəyi görməli, idarə etməli və ya anlamalıdır", "Növbəti sübut nöqtəsi: daha bir qurma işini qazandıran davranış və ya söhbət"] },
    { type: "h2", text: "İstifadə etdiyimiz əhatə dairəsi sınağı", id: "scope-test" }, { type: "p", text: "Təklif olunan hər funksiyanı götürün və bir sual verin: bu, ilk istifadəçi üçün əsas dövrənin uğurlu olma ehtimalını artırırmı? Cavab yoxdursa, onu ilk buraxılışdan çıxarın. Cavab bəlkədirsə, qoruduğu fərziyyəni yazın və həmin fərziyyəni sınaqdan keçirməyin daha ucuz yolunu tapın. Bu, faydalı funksiyanın məhsulu gecikdirmək üçün daimi bəhanəyə çevrilməsinin qarşısını alır." },
    { type: "quote", text: "Brifin məqsədi qura biləcəyiniz hər şeyi qeyd etmək deyil. Məqsədi növbəti qurma qərarını aydın etməkdir.", cite: "məhsul başlanğıclarında istifadə etdiyimiz qayda" },
    { type: "callout", title: "Bunu Start Apps Studio-da necə istifadə edirik", text: "Qurmanı qiymətləndirməzdən əvvəl təsisçinin ideyasını bir səhifəlik əhatə dairəsinə çeviririk: bir istifadəçi, bir əsas dövrə, onu dəstəkləyən ekranlar və infrastruktur, habelə növbəti qərarı dəyişməli olan sübut. Sənəd strategiya, dizayn, mühəndislik və istifadəyəvermə arasında təhvilverməyə — və yeni funksiya birinci versiyaya gizlicə daxil olmağa çalışanda istinad nöqtəsinə çevrilir." },
    { type: "h2", text: "Tez-tez verilən suallar", id: "faq" }, { type: "faq", items: [
      { q: "MVP brifi nə qədər uzun olmalıdır?", a: "Bir oturuşda oxunacaq qədər qısa və seçimlər etmək üçün kifayət qədər konkret olmalıdır. İlk istifadəçini, əsas dövrəni, istifadəyəvermə sərhədini, etibar tələblərini və növbəti sübut nöqtəsini adlandırdıqda bir-iki səhifə adətən yetərlidir." }, { q: "Brifə tam funksiya siyahısı daxil edilməlidirmi?", a: "Əsas dövrəni işlədən funksiyaları daxil edin, qalanını isə sonrakı ideyalar bölməsində saxlayın. Ayrı gözləmə siyahısı yaxşı ideyaları qoruyur, amma onların sakitcə istifadəyəvermə tələbinə çevrilməsinə imkan vermir." }, { q: "Hədəf istifadəçi hələ də qeyri-müəyyəndirsə nə etməli?", a: "Ən güclü iki namizədi və onları bir-birindən ayıracaq sübutları yazın. Qeyri-müəyyənlik açıq olduqda faydalıdır; geniş məhsul əhatə dairəsində gizləndikdə bahalı olur." }, { q: "Dizayn başlamazdan əvvəl brif bitməlidirmi?", a: "İlk dizayn keçidinə istiqamət vermək üçün kifayət qədər aydın olmalıdır, əbədi olaraq donmuş deyil. Dizayn daha yaxşı sualı üzə çıxara bilər, lakin hər dəyişiklik əhatə dairəsini və toplamağa çalışdığınız sübutu yeniləməlidir." },
    ] },
  ] },
};

export default AZ_EDITORIAL_CONTENT;