import { type LocaleEditorialContent } from "../editorial";
import { getPost } from "../posts";
const sourcePost = getPost("the-mvp-brief-is-your-first-product-decision");
if (!sourcePost) throw new Error("Quellartikel fehlt.");
export const DE_EDITORIAL_CONTENT: LocaleEditorialContent = {
  copy: { journalName: "Das Journal · Bd. I", journalTitle: "Feldnotizen aus dem Studio.", journalDescription: "Berichte über das Veröffentlichen von MVPs, die bei Google ranken und von KI zitiert werden: GEO, Vibe-Coding und der Stand von KI bei der Arbeit.", resourcesTitle: "Baue das Richtige – und baue es gut.", resourcesDescription: "Praktische Ressourcen zu Produktstrategie, KI-gestützter Umsetzung, Technologieentscheidungen, Eigentum, Übergabe und dem Start eines MVP.", read: "Notiz lesen", minutes: "Min. Lesezeit", allNotes: "Alle Notizen", sources: "Quellen", shortAnswer: "Kurzantwort", language: "Sprache", translatedArticleTitle: "Das MVP-Briefing ist Ihre erste Produktentscheidung", translatedArticleDescription: "Ein hilfreiches MVP-Briefing benennt den ersten Nutzer, setzt die Grenze von Version eins und definiert die Belege für die nächste Entscheidung." },
  resources: { title: "Baue das Richtige – und baue es gut.", description: "Praktische Ressourcen zu Produktstrategie, KI-gestützter Umsetzung, Technologieentscheidungen, Eigentum, Übergabe und dem Start eines MVP.", eyebrow: "Start Apps Studio · Ressourcen", primaryAction: "Über Ihr Projekt sprechen", journalAction: "Das Journal lesen",
    routes: { title: "Wählen Sie den nächsten Weg", intro: "Der richtige erste Meilenstein hängt davon ab, was Sie beweisen müssen – nicht davon, wie viel Software Sie sich vorstellen können.", cards: [
      { kicker: "01 · Richtung", title: "Beginnen Sie mit dem kleinsten nützlichen Beweis", text: "Eine Launch-Website beantwortet, ob Menschen das Angebot verstehen. Ein Prototyp beantwortet, ob sie auf das Erlebnis reagieren können. Ein MVP beantwortet, was echte Nutzer tun.", bullets: ["Wählen Sie eine Entscheidung, die das nächste Release ermöglichen muss", "Halten Sie die erste Version eng genug, um daraus zu lernen", "Wählen Sie das Paket, das zu den benötigten Belegen passt"] },
      { kicker: "02 · KI-gestützte Umsetzung", title: "Geschwindigkeit ist nützlich, wenn die Struktur trägt", text: "KI kann Exploration, Programmierung und Prüfung beschleunigen. Sie ersetzt weder Produkturteil, Architektur und Tests noch die verantwortliche Person.", bullets: ["Nutzen Sie KI, um Optionen zu erkunden und Wiederholungen zu verringern", "Prüfen Sie generierten Code an echten Nutzerabläufen", "Halten Sie das ausgelieferte System verständlich und erweiterbar"] },
      { kicker: "03 · Eigentum", title: "Fragen Sie, was bei der Übergabe ankommt", text: "Ein erfolgreicher Build ist mehr als eine Abschlusspräsentation. Quellcode, Designdateien, Konten, Deployment-Zugang und Kontext sollten für Sie oder Ihr nächstes Team bereitstehen.", bullets: ["Klären Sie, wem Konten und Arbeitsdateien gehören", "Prüfen Sie funktionierenden Fortschritt vor der letzten Woche", "Gehen Sie mit einer dokumentierten, wartbaren Grundlage"] },
      { kicker: "04 · Partner-Fit", title: "Vergleichen Sie die Arbeitsweise", text: "Vergleichen Sie vor der Wahl eines Produktpartners Umfangsklarheit, Feedbackschleifen, Verantwortung, Unterstützung nach dem Start und ob der Weg zur Phase Ihres Unternehmens passt.", bullets: ["Wer trifft die Produktentscheidungen?", "Wann sehen Sie etwas Reales?", "Kann ein anderes Team ohne Neustart weitermachen?"] },
    ] },
    packages: { title: "Leitfaden für Paketwege", intro: "Nutzen Sie die öffentlichen Pakete als Ausgangspunkt für das Gespräch. Der Umfang wird vor Arbeitsbeginn vereinbart.", columns: ["Weg", "Investition", "Typischer Zeitraum", "Am besten, wenn Sie"], rows: [{ route: "Launch-Website", investment: "$2,600", timing: "3–5 Arbeitstage", bestFor: "Das Angebot erklären und eine glaubwürdige digitale Präsenz schaffen" }, { route: "Prototyp", investment: "$6,000", timing: "5–10 Tage", bestFor: "Eine Idee für Validierung, Finanzierung oder frühe Gespräche greifbar machen" }, { route: "MVP", investment: "$15,000–$30,000", timing: "3–8 Wochen", bestFor: "Ein echtes Web-, iOS- oder Android-Produkt in Nutzerhände geben" }, { route: "Individuell", investment: "$25,000", timing: "1–6 Monate", bestFor: "Ein größeres oder komplexeres System mit langfristiger Verantwortung bauen" }] },
    toolkit: { title: "Das Werkzeugset hinter der Arbeit", intro: "Werkzeuge werden für das Produktergebnis, das übernehmende Team und die Unternehmensphase ausgewählt.", groups: [
      { label: "Ihre Idee, sichtbar gemacht", description: "Wie ein Konzept zu Bildschirmen wird, die Sie antippen, mit Investoren teilen und mit echten Nutzern testen können.", tools: [{ name: "Figma", note: "jeder Bildschirm vor dem Code entworfen", tone: "figma" }, { name: "Rork", note: "in wenigen Tagen auf einem echten Telefon testen", tone: "rork" }, { name: "Lovable", note: "Launch-Website in wenigen Tagen online", tone: "lovable" }, { name: "Replit", note: "funktionierendes Produkt, das Sie ausführen und bearbeiten können", tone: "replit" }] },
      { label: "Ihr Produkt, für Dauer gebaut", description: "Die Technik hinter der App, die Ihre Nutzer installieren, öffnen und bezahlen.", tools: [{ name: "React Native", note: "eine Codebasis, iOS + Android", tone: "expo" }, { name: "Swift", note: "natives iOS, am schnellsten auf dem iPhone", tone: "swift" }, { name: "Kotlin", note: "natives Android, volle Play-Store-Reichweite", tone: "kotlin" }, { name: "Node + PostgreSQL", note: "Ihre Daten, sicher und exportierbar", tone: "node" }] },
      { label: "Umsatz und Start, vom ersten Tag an", description: "Zahlungen, Updates und Codesicherheit von Beginn an integriert statt später angefügt.", open: true, tools: [{ name: "Stripe", note: "Einmalzahlungen, Abonnements, Upgrades", tone: "stripe" }, { name: "RevenueCat", note: "Abrechnung für App Store und Play Store", tone: "revenuecat" }, { name: "GitHub", note: "tägliche Backups: Ihr Code ist immer sicher", tone: "github" }, { name: "Automation", note: "n8n + Make erledigen die Routinearbeit", tone: "hooks" }] },
      { label: "KI im Hintergrund, nicht im Weg", description: "KI kann Recherche, Umsetzung und Prüfung unterstützen, während ein Mensch Richtung und Qualitätsmaßstab verantwortet.", tools: [{ name: "Claude", note: "primärer Builder und Code-Reviewer", tone: "claude" }, { name: "Gemini", note: "prüft das ganze Produkt auf einmal", tone: "gemini" }, { name: "GPT-5", note: "Texte, Abläufe und kreative Richtung", tone: "gpt" }, { name: "Llama 4", note: "selbstgehostete Option für sensible Arbeit", tone: "llama" }] },
    ], footnote: "Sie behalten Code, Konten und Arbeitsdateien. Wenn ein besseres Werkzeug erscheint, lässt es sich austauschen, ohne Ihr Produkt als Geisel zu halten." },
    journal: { title: "Feldnotizen aus dem Journal", text: "Längere Notizen über MVP-Strategie, SEO, GEO, Vibe-Coding-Apps und Entscheidungen, die ein Produkt leichter veröffentlichen lassen.", readAction: "Notiz lesen", minutesLabel: "Min. Lesezeit", allAction: "Alle Journalnotizen", fallbackCategory: "Journal", postSlugs: ["base44-vs-lovable-which-one-for-your-next-app", "the-mvp-brief-is-your-first-product-decision", "make-your-brand-visible-in-chatgpt", "vibe-coded-apps-have-an-seo-problem", "backlinks-still-decide-who-gets-recommended", "ai-overviews-citation-playbook-for-mvps"] }, cta: { title: "Haben Sie einen Weg im Sinn?", text: "Teilen Sie, wo Sie stehen, was Sie beweisen müssen und was derzeit feststeckt.", action: "Einen klaren nächsten Schritt erhalten" } },
  post: { ...sourcePost, title: "Das MVP-Briefing ist Ihre erste Produktentscheidung", seoTitle: "MVP-Briefings: Ihre erste Produktentscheidung | Start Apps Studio", description: "Ein hilfreiches MVP-Briefing beschreibt nicht nur eine Idee. Es benennt den Nutzer, zieht eine klare Grenze um Version eins und definiert die Belege dafür, ob Sie weiterbauen sollten.", seoDescription: "Ihr MVP-Briefing ist eine Produktentscheidung, keine Bürokratie. Erfahren Sie, welche drei Dinge ein hilfreiches Briefing vor Design oder Code definieren muss.", excerpt: "Die besten MVP-Briefings sind nicht lang. Sie entscheiden, für wen das Produkt ist, was Version eins nicht tun wird und welche Belege die nächste Arbeitswoche verdienen.", category: "Feldnotizen", tags: ["MVP", "Produktstrategie", "Gründer", "Umfang"], body: [
    { type: "answer", text: "Ein hilfreiches MVP-Briefing trifft vor Beginn des Designs drei Entscheidungen: Für wen das Produkt ist, was Version eins bewusst auslässt und welche Nutzerbelege die nächste Investition rechtfertigen. Deshalb ist das Briefing keine Bürokratie. Es ist die erste Produktentscheidung." }, { type: "p", text: "Gründer kommen oft mit einem Briefing, das eigentlich eine Ideenbeschreibung ist: einige Absätze über den Markt, eine Funktionsliste und ein Satz darüber, wohin das Produkt eines Tages gehen könnte. Das reicht für ein Gespräch, aber nicht für die Umsetzung. Ein Build-Team braucht ein kleineres, schärferes Dokument, das Ehrgeiz in eine Folge testbarer Entscheidungen verwandelt." },
    { type: "h2", text: "Ein hilfreiches Briefing erfüllt drei Aufgaben", id: "three-jobs" }, { type: "h3", text: "1. Es benennt die Person mit dem Problem", id: "name-the-user" }, { type: "p", text: "„Kleine Unternehmen“ sind ein Markt. Sie sind kein erster Nutzer. Ein gutes Briefing benennt die Person, ihren Moment und die Notlösung, die sie heute verwendet. Ein Praxismanager, der morgige Absagen füllen will, hat ein anderes Problem als ein Patient, der einen neuen Termin sucht, auch wenn beide zum Gesundheitswesen gehören. Je konkreter der erste Nutzer ist, desto leichter lässt sich entscheiden, was das Produkt als Nächstes tun soll." },
    { type: "h3", text: "2. Es zieht eine Linie um Version eins", id: "draw-the-line" }, { type: "p", text: "Eine Funktionsliste zeigt, was vorgestellt wurde. Eine Umfangsgrenze zeigt, was gebaut wird. Schreiben Sie die Kernschleife in einen Satz und listen Sie dann die Arbeit auf, die sie zuverlässig macht: den Hauptbildschirm, die eine sinnvolle Aktion, die Daten dahinter und das Feedback, das dem Nutzer zeigt, dass sie funktioniert hat. Alles andere ist ein Kandidat für später, keine stille Voraussetzung für den Start." },
    { type: "h3", text: "3. Es definiert den nächsten Beweis", id: "define-the-proof" }, { type: "p", text: "„Starten und sehen, was passiert“ ist kein Lernplan. Entscheiden Sie, was Sie in den ersten Wochen erwarten: einen abgeschlossenen Ablauf, eine wiederholte Aktion, eine bezahlte Conversion oder ein vom Gründer geführtes Interview mit einem bestimmten Nutzertyp. Die Messung muss nicht ausgefeilt sein. Sie muss dem Verhalten des Nutzers nahe genug sein, um die nächste Produktentscheidung ändern zu können." },
    { type: "h2", text: "Was vor einem Bildschirm aufzuschreiben ist", id: "before-a-screen" }, { type: "ul", items: ["Der erste Nutzer: eine Rolle, eine Situation und eine schmerzhafte Notlösung", "Die Kernschleife: die kleinste Aktion, die Wert schafft und wiederholt stattfinden kann", "Die Startgrenze: was für Version eins ausdrücklich außerhalb des Umfangs liegt", "Die Vertrauensanforderung: was der Nutzer sehen, kontrollieren oder verstehen muss, bevor er handelt", "Der nächste Beleg: das Verhalten oder Gespräch, das eine weitere Umsetzungsrunde verdient"] },
    { type: "h2", text: "Der Umfangstest, den wir verwenden", id: "scope-test" }, { type: "p", text: "Nehmen Sie jede vorgeschlagene Funktion und stellen Sie eine Frage: Macht sie den Erfolg der Kernschleife für den ersten Nutzer wahrscheinlicher? Wenn die Antwort nein ist, verschieben Sie sie aus dem ersten Release. Wenn sie vielleicht lautet, notieren Sie die Annahme, die sie schützt, und finden Sie einen günstigeren Weg, diese Annahme zu testen. So wird eine nützliche Funktion nicht zur dauerhaften Ausrede, das Produkt zu verzögern." }, { type: "quote", text: "Das Ziel eines Briefings ist nicht, alles festzuhalten, was Sie bauen könnten. Es soll die nächste Build-Entscheidung offensichtlich machen.", cite: "eine Regel, die wir bei Produkt-Kickoffs verwenden" },
    { type: "callout", title: "Wie wir dies bei Start Apps Studio nutzen", text: "Bevor wir einen Build anbieten, verwandeln wir die Gründeridee in einen einseitigen Umfang: ein Nutzer, eine Kernschleife, die Bildschirme und Infrastruktur, die sie tragen, und die Belege, die die nächste Entscheidung ändern sollten. Das Dokument wird zur Übergabe zwischen Strategie, Design, Engineering und Start – und zum Bezugspunkt, wenn sich eine neue Funktion in Version eins einschleichen möchte." },
    { type: "h2", text: "Häufig gestellte Fragen", id: "faq" }, { type: "faq", items: [{ q: "Wie lang sollte ein MVP-Briefing sein?", a: "Kurz genug, um es in einem Zug zu lesen, und konkret genug für Abwägungen. Ein bis zwei Seiten reichen meist, wenn sie den ersten Nutzer, die Kernschleife, die Startgrenze, Vertrauensanforderungen und den nächsten Beleg benennen." }, { q: "Sollte das Briefing eine vollständige Funktionsliste enthalten?", a: "Nehmen Sie die Funktionen auf, die die Kernschleife zum Funktionieren bringen, und bewahren Sie den Rest in einem Bereich für spätere Ideen auf. Ein separater Parkplatz schützt gute Ideen, ohne dass sie still zu Startanforderungen werden." }, { q: "Was, wenn der Zielnutzer noch unsicher ist?", a: "Notieren Sie die zwei stärksten Kandidaten und die Belege, die sie unterscheiden würden. Unsicherheit ist nützlich, wenn sie ausdrücklich ist; sie wird teuer, wenn sie in einem breiten Produktumfang verborgen bleibt." }, { q: "Muss das Briefing fertig sein, bevor das Design beginnt?", a: "Es sollte klar genug sein, um den ersten Design-Durchgang zu führen, nicht für immer eingefroren. Design darf eine bessere Frage aufdecken, aber jede Änderung sollte Umfang und den Beleg aktualisieren, den Sie sammeln wollen." }] },
  ] },
};
export default DE_EDITORIAL_CONTENT;