import { type LocaleEditorialContent } from "../editorial";
import { getPost } from "../posts";
import { ES_TRANSLATED_POSTS } from "./es-posts";

const sourcePost = getPost("the-mvp-brief-is-your-first-product-decision");
if (!sourcePost) throw new Error("No se encontró el artículo de origen.");

export const ES_EDITORIAL_CONTENT: LocaleEditorialContent = {
  copy: { journalName: "El Journal · Vol. I", journalTitle: "Notas de campo del estudio.", journalDescription: "Crónicas sobre lanzar MVP que posicionan en Google y reciben citas de IA: GEO, vibe-coding y el estado de la IA en el trabajo.", resourcesTitle: "Construye lo correcto y luego constrúyelo bien.", resourcesDescription: "Recursos prácticos sobre estrategia de producto, entrega asistida por IA, decisiones tecnológicas, propiedad, traspaso y lanzamiento de un MVP.", read: "Leer nota", minutes: "min de lectura", allNotes: "Todas las notas", sources: "Fuentes", shortAnswer: "Respuesta corta", language: "Idioma", translatedArticleTitle: "El brief de MVP es tu primera decisión de producto", translatedArticleDescription: "Un brief de MVP útil nombra al primer usuario, delimita la versión uno y define la evidencia para la siguiente decisión." },
  resources: {
    title: "Construye lo correcto y luego constrúyelo bien.", description: "Recursos prácticos sobre estrategia de producto, entrega asistida por IA, decisiones tecnológicas, propiedad, traspaso y lanzamiento de un MVP.", eyebrow: "Start Apps Studio · Recursos", primaryAction: "Habla sobre tu proyecto", journalAction: "Leer el Journal",
    routes: { title: "Elige la siguiente ruta", intro: "El hito inicial adecuado depende de lo que necesitas demostrar, no de cuánto software puedes imaginar.", cards: [
      { kicker: "01 · Dirección", title: "Empieza con la prueba útil más pequeña", text: "Un sitio de lanzamiento responde si la gente entiende la oferta. Un prototipo responde si puede reaccionar a la experiencia. Un MVP responde qué hacen los usuarios reales.", bullets: ["Elige una decisión que la próxima versión debe desbloquear", "Mantén la primera versión lo bastante acotada para aprender de ella", "Usa el paquete que se ajuste a la evidencia que necesitas"] },
      { kicker: "02 · Entrega asistida por IA", title: "La velocidad sirve cuando la estructura se sostiene", text: "La IA puede acelerar la exploración, la programación y la revisión. No sustituye el criterio de producto, la arquitectura, las pruebas ni a la persona responsable del resultado.", bullets: ["Usa IA para explorar opciones y reducir repeticiones", "Revisa el código generado frente a flujos reales de usuarios", "Mantén el sistema entregado comprensible y extensible"] },
      { kicker: "03 · Propiedad", title: "Pregunta qué se entrega en el traspaso", text: "Un proyecto exitoso es más que una presentación final. El código fuente, los archivos de diseño, las cuentas, el acceso al despliegue y el contexto deben quedar listos para ti o tu siguiente equipo.", bullets: ["Confirma quién posee las cuentas y los archivos de trabajo", "Revisa el progreso real antes de la última semana", "Termina con una base documentada y mantenible"] },
      { kicker: "04 · Afinidad con el socio", title: "Compara la forma de trabajar", text: "Antes de elegir un socio de producto, compara la claridad del alcance, los ciclos de feedback, la responsabilidad, el apoyo tras el lanzamiento y si la ruta encaja con la etapa de tu empresa.", bullets: ["¿Quién toma las decisiones de producto?", "¿Cuándo verás algo real?", "¿Puede otro equipo continuar sin empezar de cero?"] },
    ] },
    packages: { title: "Guía de rutas de paquetes", intro: "Usa los paquetes públicos como punto de partida para la conversación. El alcance se acuerda antes de empezar.", columns: ["Ruta", "Inversión", "Plazo habitual", "Ideal cuando necesitas"], rows: [
      { route: "Sitio de lanzamiento", investment: "$2,600", timing: "3–5 días laborables", bestFor: "Explicar la oferta y crear una presencia digital creíble" }, { route: "Prototipo", investment: "$6,000", timing: "5–10 días", bestFor: "Hacer tangible una idea para validación, financiación o conversaciones iniciales" }, { route: "MVP", investment: "$15,000–$30,000", timing: "3–8 semanas", bestFor: "Poner un producto web, iOS o Android real en manos de usuarios" }, { route: "Personalizado", investment: "$25,000", timing: "1–6 meses", bestFor: "Crear un sistema más grande o complejo con responsabilidad a largo plazo" },
    ] },
    toolkit: { title: "Las herramientas detrás del trabajo", intro: "Las herramientas se eligen según el resultado del producto, el equipo que lo asumirá y la etapa de la empresa.", groups: [
      { label: "Tu idea, hecha visible", description: "Cómo un concepto se convierte en pantallas que puedes tocar, compartir con inversores y probar con usuarios reales.", tools: [{ name: "Figma", note: "cada pantalla diseñada antes del código", tone: "figma" }, { name: "Rork", note: "pruébalo en un teléfono real en días", tone: "rork" }, { name: "Lovable", note: "sitio de lanzamiento activo en días", tone: "lovable" }, { name: "Replit", note: "producto funcional que puedes ejecutar y editar", tone: "replit" }] },
      { label: "Tu producto, creado para durar", description: "La ingeniería que impulsa la aplicación que tus usuarios instalan, abren y pagan.", tools: [{ name: "React Native", note: "una base de código, iOS + Android", tone: "expo" }, { name: "Swift", note: "iOS nativo, más rápido en iPhone", tone: "swift" }, { name: "Kotlin", note: "Android nativo, alcance total de Play Store", tone: "kotlin" }, { name: "Node + PostgreSQL", note: "tus datos, seguros y exportables", tone: "node" }] },
      { label: "Ingresos y lanzamiento, desde el primer día", description: "Pagos, actualizaciones y seguridad del código integrados desde el inicio, no añadidos después.", open: true, tools: [{ name: "Stripe", note: "pagos únicos, suscripciones, mejoras", tone: "stripe" }, { name: "RevenueCat", note: "facturación de App Store y Play Store", tone: "revenuecat" }, { name: "GitHub", note: "copias diarias: tu código siempre está seguro", tone: "github" }, { name: "Automation", note: "n8n + Make resuelven el trabajo repetitivo", tone: "hooks" }] },
      { label: "IA en segundo plano, no en tu camino", description: "La IA puede apoyar la investigación, implementación y revisión mientras una persona asume la dirección y el estándar de calidad.", tools: [{ name: "Claude", note: "constructor principal y revisor de código", tone: "claude" }, { name: "Gemini", note: "revisa todo el producto de una vez", tone: "gemini" }, { name: "GPT-5", note: "textos, flujos y dirección creativa", tone: "gpt" }, { name: "Llama 4", note: "opción autoalojada para trabajo sensible", tone: "llama" }] },
    ], footnote: "Conservas el código, las cuentas y los archivos de trabajo. Cuando aparezca una herramienta mejor, puede sustituirse sin dejar tu producto cautivo." },
    journal: { title: "Notas de campo del Journal", text: "Notas extensas sobre estrategia de MVP, SEO, GEO, aplicaciones creadas con vibe-coding y las decisiones que facilitan lanzar un producto.", readAction: "Leer nota", minutesLabel: "min de lectura", allAction: "Todas las notas del journal", fallbackCategory: "Journal", postSlugs: ["base44-vs-lovable-which-one-for-your-next-app", "the-mvp-brief-is-your-first-product-decision", "make-your-brand-visible-in-chatgpt", "vibe-coded-apps-have-an-seo-problem", "backlinks-still-decide-who-gets-recommended", "ai-overviews-citation-playbook-for-mvps"] },
    cta: { title: "¿Tienes una ruta en mente?", text: "Cuéntanos dónde estás, qué necesitas demostrar y qué está atascado ahora.", action: "Obtén un siguiente paso claro" },
  },
  post: { ...sourcePost, title: "El brief de MVP es tu primera decisión de producto", seoTitle: "Briefs de MVP: tu primera decisión de producto | Start Apps Studio", description: "Un brief de MVP útil hace más que describir una idea. Nombra al usuario, traza una línea firme alrededor de la versión uno y define la evidencia que indica si debes seguir construyendo.", seoDescription: "Tu brief de MVP es una decisión de producto, no papeleo. Conoce las tres cosas que un brief útil debe definir antes de empezar diseño o código.", excerpt: "Los mejores briefs de MVP no son largos. Deciden para quién es el producto, qué se niega a hacer la versión uno y qué evidencia merece la siguiente semana de trabajo.", category: "Notas de campo", tags: ["MVP", "Estrategia de producto", "Fundadores", "Alcance"], body: [
    { type: "answer", text: "Un brief de MVP útil toma tres decisiones antes de que empiece el diseño: para quién es el producto, qué dejará fuera deliberadamente la versión uno y qué evidencia de usuarios justificará la siguiente inversión. Por eso el brief no es papeleo. Es la primera decisión de producto." }, { type: "p", text: "Los fundadores suelen llegar con un brief que en realidad es una descripción de la idea: unos párrafos sobre el mercado, una lista de funciones y una frase sobre hacia dónde podría ir el producto algún día. Basta para iniciar una conversación, pero no para entregar. Un equipo de desarrollo necesita un documento más pequeño y preciso que convierta la ambición en una secuencia de decisiones comprobables." },
    { type: "h2", text: "Un brief útil cumple tres funciones", id: "three-jobs" }, { type: "h3", text: "1. Nombra a la persona que tiene el problema", id: "name-the-user" }, { type: "p", text: "«Pequeñas empresas» es un mercado. No es un primer usuario. Un buen brief nombra a la persona, el momento en que se encuentra y la solución provisional que usa hoy. Un gestor de clínica que intenta cubrir las cancelaciones de mañana tiene un problema diferente de un paciente que busca una nueva cita, aunque ambos pertenezcan a la sanidad. Cuanto más específico sea el primer usuario, más fácil será decidir qué debe hacer el producto después." },
    { type: "h3", text: "2. Traza una línea alrededor de la versión uno", id: "draw-the-line" }, { type: "p", text: "Una lista de funciones indica lo que se ha imaginado. Una línea de alcance indica lo que se construirá. Escribe el ciclo central en una frase y luego enumera el trabajo que lo hace fiable: la pantalla principal, la única acción significativa, los datos que la sustentan y la señal que indica al usuario que funcionó. Todo lo demás es candidato para más adelante, no un requisito silencioso para el lanzamiento." },
    { type: "h3", text: "3. Define la prueba que viene después", id: "define-the-proof" }, { type: "p", text: "«Lanzar y ver qué pasa» no es un plan de aprendizaje. Decide qué esperas observar en las primeras semanas: un flujo completado, una acción repetida, una conversión de pago o una entrevista dirigida por el fundador con un tipo específico de usuario. La medida no tiene que ser sofisticada. Debe estar suficientemente cerca del comportamiento del usuario como para cambiar la siguiente decisión de producto." },
    { type: "h2", text: "Qué anotar antes de una pantalla", id: "before-a-screen" }, { type: "ul", items: ["El primer usuario: un rol, una situación y una solución provisional dolorosa", "El ciclo central: la acción más pequeña que crea valor y puede repetirse", "El límite de lanzamiento: lo que queda explícitamente fuera del alcance de la versión uno", "El requisito de confianza: lo que el usuario debe ver, controlar o entender antes de actuar", "La siguiente prueba: el comportamiento o conversación que merece otra ronda de trabajo"] },
    { type: "h2", text: "La prueba de alcance que usamos", id: "scope-test" }, { type: "p", text: "Toma cada función propuesta y haz una pregunta: ¿hace que el ciclo central tenga más probabilidades de funcionar para el primer usuario? Si la respuesta es no, sáquela de la primera versión. Si es quizá, anota el supuesto que protege y busca una forma más barata de probarlo. Esto evita que una función útil se convierta en una excusa permanente para retrasar el producto." }, { type: "quote", text: "El objetivo de un brief no es capturar todo lo que podrías construir. Es hacer evidente la siguiente decisión de desarrollo.", cite: "una regla que usamos al iniciar productos" },
    { type: "callout", title: "Cómo usamos esto en Start Apps Studio", text: "Antes de presupuestar un desarrollo, convertimos la idea del fundador en un alcance de una página: un usuario, un ciclo central, las pantallas e infraestructura que lo respaldan y la evidencia que debería cambiar la siguiente decisión. El documento se convierte en el traspaso entre estrategia, diseño, ingeniería y lanzamiento, y en el punto de referencia cuando una nueva función intenta colarse en la versión uno." },
    { type: "h2", text: "Preguntas frecuentes", id: "faq" }, { type: "faq", items: [{ q: "¿Cuánto debe medir un brief de MVP?", a: "Lo bastante corto para leerse de una sentada y lo bastante específico para tomar decisiones. Una o dos páginas suelen bastar cuando nombran al primer usuario, el ciclo central, el límite de lanzamiento, los requisitos de confianza y la siguiente prueba." }, { q: "¿Debe incluir el brief una lista completa de funciones?", a: "Incluye las funciones que hacen funcionar el ciclo central y guarda el resto en una sección de ideas posteriores. Un aparcamiento separado protege buenas ideas sin dejar que se conviertan silenciosamente en requisitos de lanzamiento." }, { q: "¿Qué ocurre si el usuario objetivo aún es incierto?", a: "Anota los dos candidatos más sólidos y la evidencia que los distinguiría. La incertidumbre sirve cuando es explícita; se vuelve cara cuando queda oculta dentro de un alcance de producto amplio." }, { q: "¿Debe terminarse el brief antes de empezar el diseño?", a: "Debe ser suficientemente claro para guiar la primera pasada de diseño, no quedar congelado para siempre. El diseño puede revelar una pregunta mejor, pero cada cambio debe actualizar el alcance y la prueba que intentas reunir." }] },
  ] },
  translatedPosts: ES_TRANSLATED_POSTS,
};
export default ES_EDITORIAL_CONTENT;