import { type LocaleEditorialContent } from "../editorial";
import { getPost } from "../posts";

const sourcePost = getPost("the-mvp-brief-is-your-first-product-decision");
if (!sourcePost) throw new Error("Article source introuvable.");

export const FR_EDITORIAL_CONTENT: LocaleEditorialContent = {
  copy: {
    journalName: "Le Journal · Vol. I", journalTitle: "Notes de terrain du studio.",
    journalDescription: "Réflexions sur le lancement de MVP qui se positionnent sur Google et sont cités par l’IA : GEO, vibe-coding et l’état de l’IA au travail.",
    resourcesTitle: "Construisez la bonne chose, puis construisez-la bien.",
    resourcesDescription: "Des ressources pratiques sur la stratégie produit, la livraison assistée par IA, les choix technologiques, la propriété, la passation et le lancement d’un MVP.",
    read: "Lire la note", minutes: "min de lecture", allNotes: "Toutes les notes", sources: "Sources", shortAnswer: "Réponse courte", language: "Langue",
    translatedArticleTitle: "Le brief MVP est votre première décision produit",
    translatedArticleDescription: "Un brief MVP utile identifie le premier utilisateur, fixe la limite de la version un et définit les preuves nécessaires à la prochaine décision.",
  },
  resources: {
    title: "Construisez la bonne chose, puis construisez-la bien.",
    description: "Des ressources pratiques sur la stratégie produit, la livraison assistée par IA, les choix technologiques, la propriété, la passation et le lancement d’un MVP.",
    eyebrow: "Start Apps Studio · Ressources", primaryAction: "Parler de votre projet", journalAction: "Lire le Journal",
    routes: { title: "Choisissez la prochaine voie", intro: "La bonne première étape dépend de ce que vous devez prouver, pas de la quantité de logiciel que vous pouvez imaginer.", cards: [
      { kicker: "01 · Direction", title: "Commencez par la plus petite preuve utile", text: "Un site de lancement répond à la question de savoir si les gens comprennent l’offre. Un prototype répond à la question de savoir s’ils réagissent à l’expérience. Un MVP répond à ce que font de vrais utilisateurs.", bullets: ["Choisissez une décision que la prochaine version doit permettre", "Gardez la première version assez ciblée pour en tirer des enseignements", "Utilisez l’offre qui correspond aux preuves dont vous avez besoin"] },
      { kicker: "02 · Livraison assistée par IA", title: "La vitesse est utile quand la structure tient", text: "L’IA peut accélérer l’exploration, le code et la revue. Elle ne remplace ni le jugement produit, ni l’architecture, les tests ou la personne responsable du résultat.", bullets: ["Utilisez l’IA pour explorer des options et réduire les répétitions", "Vérifiez le code généré par rapport aux vrais parcours utilisateurs", "Gardez le système livré compréhensible et extensible"] },
      { kicker: "03 · Propriété", title: "Demandez ce qui est remis lors de la passation", text: "Une réalisation réussie ne se résume pas à une présentation finale. Le code source, les fichiers de conception, les comptes, l’accès au déploiement et le contexte doivent être prêts pour vous ou votre prochaine équipe.", bullets: ["Confirmez à qui appartiennent les comptes et les fichiers de travail", "Examinez l’avancement réel avant la dernière semaine", "Repartez avec une base documentée et maintenable"] },
      { kicker: "04 · Compatibilité partenaire", title: "Comparez la manière de travailler", text: "Avant de choisir un partenaire produit, comparez la clarté du périmètre, les boucles de retour, les responsabilités, l’accompagnement après lancement et l’adéquation de la voie au stade de votre entreprise.", bullets: ["Qui prend les décisions produit ?", "Quand verrez-vous quelque chose de concret ?", "Une autre équipe peut-elle continuer sans repartir de zéro ?"] },
    ] },
    packages: { title: "Guide d’orientation des offres", intro: "Utilisez les offres publiques comme point de départ de la discussion. Le périmètre est convenu avant le début du travail.", columns: ["Voie", "Investissement", "Délai habituel", "Idéal lorsque vous devez"], rows: [
      { route: "Site de lancement", investment: "$2,600", timing: "3–5 jours ouvrés", bestFor: "Expliquer l’offre et créer une présence numérique crédible" },
      { route: "Prototype", investment: "$6,000", timing: "5–10 jours", bestFor: "Rendre une idée tangible pour la validation, une levée de fonds ou les premières conversations" },
      { route: "MVP", investment: "$15,000–$30,000", timing: "3–8 semaines", bestFor: "Mettre un véritable produit web, iOS ou Android entre les mains des utilisateurs" },
      { route: "Sur mesure", investment: "$25,000", timing: "1–6 mois", bestFor: "Créer un système plus vaste ou complexe avec une responsabilité durable" },
    ] },
    toolkit: { title: "La boîte à outils derrière le travail", intro: "Les outils sont choisis en fonction du résultat produit, de l’équipe qui le reprendra et du stade de l’entreprise.", groups: [
      { label: "Votre idée, rendue visible", description: "Comment un concept devient des écrans que vous pouvez toucher, partager avec des investisseurs et tester avec de vrais utilisateurs.", tools: [{ name: "Figma", note: "chaque écran conçu avant le code", tone: "figma" }, { name: "Rork", note: "essayez-le sur un vrai téléphone en quelques jours", tone: "rork" }, { name: "Lovable", note: "site de lancement en ligne en quelques jours", tone: "lovable" }, { name: "Replit", note: "produit fonctionnel que vous pouvez exécuter et modifier", tone: "replit" }] },
      { label: "Votre produit, conçu pour durer", description: "L’ingénierie qui fait fonctionner l’application que vos utilisateurs installent, ouvrent et paient.", tools: [{ name: "React Native", note: "une base de code, iOS + Android", tone: "expo" }, { name: "Swift", note: "iOS natif, le plus rapide sur iPhone", tone: "swift" }, { name: "Kotlin", note: "Android natif, portée complète du Play Store", tone: "kotlin" }, { name: "Node + PostgreSQL", note: "vos données, sécurisées et exportables", tone: "node" }] },
      { label: "Revenus et lancement, dès le premier jour", description: "Paiements, mises à jour et sécurité du code intégrés dès le départ, et non ajoutés après coup.", open: true, tools: [{ name: "Stripe", note: "paiements uniques, abonnements, mises à niveau", tone: "stripe" }, { name: "RevenueCat", note: "facturation App Store et Play Store", tone: "revenuecat" }, { name: "GitHub", note: "sauvegardes quotidiennes : votre code est toujours en sécurité", tone: "github" }, { name: "Automation", note: "n8n + Make s’occupent des tâches répétitives", tone: "hooks" }] },
      { label: "L’IA en arrière-plan, pas sur votre chemin", description: "L’IA peut soutenir la recherche, l’implémentation et la revue, tandis qu’une personne reste responsable de la direction et du niveau de qualité.", tools: [{ name: "Claude", note: "principal constructeur et relecteur de code", tone: "claude" }, { name: "Gemini", note: "examine le produit entier d’un coup", tone: "gemini" }, { name: "GPT-5", note: "textes, parcours et direction créative", tone: "gpt" }, { name: "Llama 4", note: "option auto-hébergée pour les travaux sensibles", tone: "llama" }] },
    ], footnote: "Vous conservez le code, les comptes et les fichiers de travail. Lorsqu’un meilleur outil arrive, il peut être remplacé sans prendre votre produit en otage." },
    journal: { title: "Notes de terrain du Journal", text: "Des notes plus longues sur la stratégie MVP, le SEO, le GEO, les applications créées en vibe-coding et les décisions qui facilitent le lancement d’un produit.", readAction: "Lire la note", minutesLabel: "min de lecture", allAction: "Toutes les notes du journal", fallbackCategory: "Journal", postSlugs: ["base44-vs-lovable-which-one-for-your-next-app", "the-mvp-brief-is-your-first-product-decision", "make-your-brand-visible-in-chatgpt", "vibe-coded-apps-have-an-seo-problem", "backlinks-still-decide-who-gets-recommended", "ai-overviews-citation-playbook-for-mvps"] },
    cta: { title: "Une voie en tête ?", text: "Dites-nous où vous en êtes, ce que vous devez prouver et ce qui bloque actuellement.", action: "Obtenir une prochaine étape claire" },
  },
  post: { ...sourcePost, title: "Le brief MVP est votre première décision produit", seoTitle: "Brief MVP : votre première décision produit | Start Apps Studio", description: "Un brief MVP utile fait plus que décrire une idée. Il identifie l’utilisateur, trace une limite nette autour de la version un et définit les preuves indiquant s’il faut continuer à construire.", seoDescription: "Votre brief MVP est une décision produit, pas de la paperasse. Découvrez les trois éléments qu’un brief utile doit définir avant le début du design ou du code.", excerpt: "Les meilleurs briefs MVP ne sont pas longs. Ils décident à qui s’adresse le produit, ce que la version un refuse de faire et quelles preuves méritent la prochaine semaine de travail.", category: "Notes de terrain", tags: ["MVP", "Stratégie produit", "Fondateurs", "Périmètre"], body: [
    { type: "answer", text: "Un brief MVP utile prend trois décisions avant le début du design : à qui s’adresse le produit, ce que la version un laissera délibérément de côté et quelles preuves utilisateurs justifieront le prochain investissement. C’est pourquoi le brief n’est pas de la paperasse. C’est la première décision produit." },
    { type: "p", text: "Les fondateurs arrivent souvent avec un brief qui est en réalité une description de l’idée : quelques paragraphes sur le marché, une liste de fonctionnalités et une phrase sur l’avenir possible du produit. C’est suffisant pour entamer une conversation, mais pas pour livrer. Une équipe de réalisation a besoin d’un document plus court et plus précis, qui transforme l’ambition en une suite de choix testables." },
    { type: "h2", text: "Un brief utile remplit trois fonctions", id: "three-jobs" }, { type: "h3", text: "1. Il identifie la personne qui a le problème", id: "name-the-user" },
    { type: "p", text: "« Les petites entreprises » désigne un marché. Ce n’est pas un premier utilisateur. Un bon brief nomme la personne, le moment qu’elle traverse et la solution de contournement qu’elle utilise aujourd’hui. Un responsable de clinique qui cherche à combler les annulations de demain a un problème différent de celui d’un patient recherchant un nouveau rendez-vous, même si tous deux appartiennent au secteur de la santé. Plus le premier utilisateur est précis, plus il devient facile de décider de ce que le produit doit faire ensuite." },
    { type: "h3", text: "2. Il trace une limite autour de la version un", id: "draw-the-line" }, { type: "p", text: "Une liste de fonctionnalités indique ce qui a été imaginé. Une limite de périmètre indique ce qui sera construit. Écrivez la boucle principale en une phrase, puis listez le travail qui la rend fiable : l’écran principal, l’action utile unique, les données qui la sous-tendent et le retour qui indique à l’utilisateur qu’elle a fonctionné. Tout le reste est candidat pour plus tard, et non une exigence implicite au lancement." },
    { type: "h3", text: "3. Il définit la prochaine preuve", id: "define-the-proof" }, { type: "p", text: "« Lançons et voyons ce qui se passe » n’est pas un plan d’apprentissage. Décidez ce que vous espérez observer dans les premières semaines : un parcours achevé, une action répétée, une conversion payante ou un entretien mené par le fondateur avec un type précis d’utilisateur. La mesure n’a pas besoin d’être sophistiquée. Elle doit être suffisamment proche du comportement de l’utilisateur pour pouvoir modifier la prochaine décision produit." },
    { type: "h2", text: "Ce qu’il faut noter avant un écran", id: "before-a-screen" }, { type: "ul", items: ["Le premier utilisateur : un rôle, une situation et une solution de contournement pénible", "La boucle principale : la plus petite action qui crée de la valeur et peut se répéter", "La limite de lancement : ce qui est explicitement hors périmètre pour la version un", "L’exigence de confiance : ce que l’utilisateur doit voir, contrôler ou comprendre avant d’agir", "La prochaine preuve : le comportement ou la conversation qui mérite un nouveau cycle de réalisation"] },
    { type: "h2", text: "Le test de périmètre que nous utilisons", id: "scope-test" }, { type: "p", text: "Prenez chaque fonctionnalité proposée et posez une question : rend-elle la réussite de la boucle principale plus probable pour le premier utilisateur ? Si la réponse est non, retirez-la de la première version. Si la réponse est peut-être, notez l’hypothèse qu’elle protège et trouvez une manière moins coûteuse de la tester. Cela évite qu’une fonctionnalité utile devienne une excuse permanente pour retarder le produit." },
    { type: "quote", text: "Le but d’un brief n’est pas de saisir tout ce que vous pourriez construire. Il est de rendre évidente la prochaine décision de réalisation.", cite: "une règle que nous appliquons au lancement des produits" },
    { type: "callout", title: "Comment nous utilisons cela chez Start Apps Studio", text: "Avant de chiffrer une réalisation, nous transformons l’idée du fondateur en un périmètre d’une page : un utilisateur, une boucle principale, les écrans et l’infrastructure qui la soutiennent, et les preuves qui devraient modifier la prochaine décision. Le document devient le relais entre stratégie, design, ingénierie et lancement — ainsi que le point de référence lorsqu’une nouvelle fonctionnalité tente de se glisser dans la version un." },
    { type: "h2", text: "Questions fréquentes", id: "faq" }, { type: "faq", items: [{ q: "Quelle devrait être la longueur d’un brief MVP ?", a: "Assez court pour être lu d’une traite et assez précis pour arbitrer. Une à deux pages suffisent généralement lorsqu’elles identifient le premier utilisateur, la boucle principale, la limite de lancement, les exigences de confiance et la prochaine preuve." }, { q: "Le brief doit-il inclure une liste complète de fonctionnalités ?", a: "Incluez les fonctionnalités qui font fonctionner la boucle principale, puis gardez le reste dans une section d’idées ultérieures. Un espace de stationnement séparé protège les bonnes idées sans les laisser devenir discrètement des exigences de lancement." }, { q: "Que faire si l’utilisateur cible reste incertain ?", a: "Notez les deux candidats les plus solides et les preuves qui les distingueraient. L’incertitude est utile lorsqu’elle est explicite ; elle devient coûteuse lorsqu’elle se cache dans un périmètre produit trop large." }, { q: "Le brief doit-il être terminé avant le début du design ?", a: "Il doit être assez clair pour guider la première étape de design, sans être figé pour toujours. Le design peut révéler une meilleure question, mais chaque changement doit mettre à jour le périmètre et la preuve que vous cherchez à recueillir." }] },
  ] },
};

export default FR_EDITORIAL_CONTENT;