import { getPost } from "../posts";
import type { LocaleEditorialContent } from "../editorial";
import { IT_TRANSLATED_POSTS } from "./it-posts";

const sourcePost = getPost("the-mvp-brief-is-your-first-product-decision");
if (!sourcePost) throw new Error("MVP source post is missing.");

export const IT_EDITORIAL_CONTENT: LocaleEditorialContent = {
  copy: { journalName: "The Journal · Vol. I", journalTitle: "Appunti dal campo dello studio.", journalDescription: "Resoconti sulla pubblicazione di MVP che si posizionano su Google e vengono citati dall'AI: GEO, vibe-coding e lo stato dell'AI al lavoro.", resourcesTitle: "Costruisci la cosa giusta, poi costruiscila bene.", resourcesDescription: "Risorse pratiche su strategia di prodotto, consegna assistita dall'AI, scelte tecnologiche, proprietà, passaggio di consegne e lancio di un MVP.", read: "Leggi l'appunto", minutes: "min di lettura", allNotes: "Tutti gli appunti", sources: "Fonti", shortAnswer: "Risposta breve", language: "Lingua", translatedArticleTitle: "Il brief dell'MVP è la tua prima decisione di prodotto", translatedArticleDescription: "Un brief MVP utile identifica il primo utente, definisce il confine della versione uno e stabilisce l'evidenza per la decisione successiva." },
  resources: {
    title: "Costruisci la cosa giusta, poi costruiscila bene.", description: "Risorse pratiche su strategia di prodotto, consegna assistita dall'AI, scelte tecnologiche, proprietà, passaggio di consegne e lancio di un MVP.", eyebrow: "Start Apps Studio · Risorse", primaryAction: "Parliamo del tuo progetto", journalAction: "Leggi il Journal",
    routes: { title: "Scegli il prossimo percorso", intro: "La giusta prima tappa dipende da ciò che devi dimostrare, non da quanto software riesci a immaginare.", cards: [
      { kicker: "01 · Direzione", title: "Inizia dalla più piccola prova utile", text: "Un sito di lancio risponde se le persone capiscono l'offerta. Un prototipo risponde se sanno reagire all'esperienza. Un MVP risponde a ciò che fanno gli utenti reali.", bullets: ["Scegli una decisione che la prossima release deve sbloccare", "Mantieni la prima versione abbastanza circoscritta da poter imparare", "Usa il pacchetto adatto all'evidenza di cui hai bisogno"] },
      { kicker: "02 · Consegna assistita dall'AI", title: "La velocità è utile quando la struttura regge", text: "L'AI può accelerare esplorazione, scrittura del codice e revisione. Non sostituisce giudizio di prodotto, architettura, test o la persona responsabile del risultato.", bullets: ["Usa l'AI per esplorare opzioni e ridurre le ripetizioni", "Rivedi il codice generato rispetto ai flussi reali degli utenti", "Mantieni il sistema pubblicato comprensibile ed estendibile"] },
      { kicker: "03 · Proprietà", title: "Chiedi cosa arriva al passaggio di consegne", text: "Una realizzazione riuscita è più di una presentazione finale. Codice sorgente, file di design, account, accesso al deployment e contesto devono essere pronti per te o per il tuo prossimo team.", bullets: ["Conferma chi possiede gli account e i file di lavoro", "Esamina i progressi funzionanti prima dell'ultima settimana", "Vai via con una base documentata e manutenibile"] },
      { kicker: "04 · Compatibilità del partner", title: "Confronta il modo di lavorare", text: "Prima di scegliere un partner di prodotto, confronta chiarezza dell'ambito, cicli di feedback, responsabilità, supporto dopo il lancio e l'adeguatezza del percorso allo stadio della tua impresa.", bullets: ["Chi prende le decisioni di prodotto?", "Quando vedrai qualcosa di reale?", "Un altro team può continuare senza ricominciare da capo?"] },
    ] },
    packages: { title: "Guida ai percorsi dei pacchetti", intro: "Usa i pacchetti pubblici come punto di partenza per la conversazione. L'ambito viene concordato prima dell'inizio del lavoro.", columns: ["Percorso", "Investimento", "Tempistica tipica", "Ideale quando devi"], rows: [
      { route: "Sito di lancio", investment: "$2,600", timing: "3–5 giorni lavorativi", bestFor: "Spiegare l'offerta e creare una presenza digitale credibile" }, { route: "Prototipo", investment: "$6,000", timing: "5–10 giorni", bestFor: "Rendere tangibile un'idea per validazione, raccolta fondi o prime conversazioni" }, { route: "MVP", investment: "$15,000–$30,000", timing: "3–8 settimane", bestFor: "Mettere un vero prodotto web, iOS o Android nelle mani degli utenti" }, { route: "Su misura", investment: "$25,000", timing: "1–6 mesi", bestFor: "Costruire un sistema più grande o complesso con responsabilità a lungo termine" },
    ] },
    toolkit: { title: "Il toolkit dietro al lavoro", intro: "Gli strumenti vengono scelti per il risultato del prodotto, il team che lo prenderà in carico e la fase dell'impresa.", groups: [
      { label: "La tua idea, resa visibile", description: "Come un concetto diventa schermate che puoi toccare, condividere con gli investitori e testare con utenti reali.", tools: [{ name: "Figma", note: "ogni schermata progettata prima del codice", tone: "figma" }, { name: "Rork", note: "provalo su un telefono vero in pochi giorni", tone: "rork" }, { name: "Lovable", note: "sito di lancio online in pochi giorni", tone: "lovable" }, { name: "Replit", note: "prodotto funzionante che puoi eseguire e modificare", tone: "replit" }] },
      { label: "Il tuo prodotto, costruito per durare", description: "L'ingegneria che alimenta l'app che i tuoi utenti installano, aprono e pagano.", tools: [{ name: "React Native", note: "un'unica base di codice, iOS + Android", tone: "expo" }, { name: "Swift", note: "iOS nativo, velocissimo su iPhone", tone: "swift" }, { name: "Kotlin", note: "Android nativo, piena copertura Play Store", tone: "kotlin" }, { name: "Node + PostgreSQL", note: "i tuoi dati, sicuri e tuoi da esportare", tone: "node" }] },
      { label: "Ricavi e lancio, dal primo giorno", description: "Pagamenti, aggiornamenti e sicurezza del codice integrati dall'inizio, non aggiunti dopo.", open: true, tools: [{ name: "Stripe", note: "una tantum, abbonamenti, upgrade", tone: "stripe" }, { name: "RevenueCat", note: "fatturazione App Store e Play Store", tone: "revenuecat" }, { name: "GitHub", note: "backup giornalieri: il tuo codice è sempre al sicuro", tone: "github" }, { name: "Automation", note: "n8n + Make gestiscono il lavoro ripetitivo", tone: "hooks" }] },
      { label: "AI sullo sfondo, non d'intralcio", description: "L'AI può supportare ricerca, implementazione e revisione, mentre una persona è responsabile della direzione e del livello qualitativo.", tools: [{ name: "Claude", note: "sviluppatore principale e revisore del codice", tone: "claude" }, { name: "Gemini", note: "esamina tutto il prodotto in una volta", tone: "gemini" }, { name: "GPT-5", note: "testi, flussi e direzione creativa", tone: "gpt" }, { name: "Llama 4", note: "opzione self-hosted per lavori sensibili", tone: "llama" }] },
    ], footnote: "Conservi codice, account e file di lavoro. Quando arriva uno strumento migliore, può essere sostituito senza tenere in ostaggio il tuo prodotto." },
    journal: { title: "Appunti dal campo del Journal", text: "Appunti più lunghi su strategia MVP, SEO, GEO, app vibe-coded e decisioni che rendono un prodotto più facile da pubblicare.", readAction: "Leggi l'appunto", minutesLabel: "min di lettura", allAction: "Tutti gli appunti del Journal", fallbackCategory: "Journal", postSlugs: ["base44-vs-lovable-which-one-for-your-next-app", "the-mvp-brief-is-your-first-product-decision", "make-your-brand-visible-in-chatgpt", "vibe-coded-apps-have-an-seo-problem", "backlinks-still-decide-who-gets-recommended", "ai-overviews-citation-playbook-for-mvps"] },
    cta: { title: "Hai in mente un percorso?", text: "Condividi dove ti trovi, cosa devi dimostrare e cosa è bloccato in questo momento.", action: "Ottieni un prossimo passo chiaro" },
  },
  post: { slug: sourcePost.slug, publishedAt: sourcePost.publishedAt, readMinutes: sourcePost.readMinutes, title: "Il brief dell'MVP è la tua prima decisione di prodotto", seoTitle: "Brief MVP: la tua prima decisione di prodotto | Start Apps Studio", description: "Un brief MVP utile fa più che descrivere un'idea. Identifica l'utente, traccia un confine netto attorno alla versione uno e definisce l'evidenza che indica se continuare a costruire.", seoDescription: "Il tuo brief MVP è una decisione di prodotto, non burocrazia. Scopri le tre cose che un brief utile deve definire prima dell'inizio di design o codice.", excerpt: "I migliori brief MVP non sono lunghi. Decidono per chi è il prodotto, cosa la versione uno rifiuta di fare e quale evidenza merita la prossima settimana di lavoro.", category: "Appunti dal campo", tags: ["MVP", "Strategia di prodotto", "Fondatori", "Ambito"], body: [
    { type: "answer", text: "Un brief MVP utile prende tre decisioni prima che inizi il design: per chi è il prodotto, cosa la versione uno lascerà deliberatamente fuori e quale evidenza degli utenti giustificherà il prossimo investimento. Ecco perché il brief non è burocrazia: è la prima decisione di prodotto." },
    { type: "p", text: "I fondatori arrivano spesso con un brief che in realtà è una descrizione dell'idea: qualche paragrafo sul mercato, un elenco di funzionalità e una frase su dove il prodotto potrebbe arrivare un giorno. Basta per avviare una conversazione, ma non per pubblicare. Un team di sviluppo ha bisogno di un documento più piccolo e più nitido, che trasformi l'ambizione in una sequenza di scelte verificabili." },
    { type: "h2", text: "Un brief utile svolge tre compiti", id: "three-jobs" }, { type: "h3", text: "1. Identifica la persona che ha il problema", id: "name-the-user" }, { type: "p", text: "“Piccole imprese” è un mercato, non un primo utente. Un buon brief identifica la persona, il momento in cui si trova e l'espediente che usa oggi. Un responsabile di clinica che cerca di riempire le cancellazioni di domani ha un problema diverso da un paziente che cerca un nuovo appuntamento, anche se entrambi appartengono alla sanità. Più è specifico il primo utente, più è facile decidere cosa debba fare il prodotto dopo." },
    { type: "h3", text: "2. Traccia una linea attorno alla versione uno", id: "draw-the-line" }, { type: "p", text: "Un elenco di funzionalità dice ciò che è stato immaginato. Un confine di ambito dice ciò che verrà costruito. Scrivi il ciclo fondamentale in una frase, poi elenca il lavoro che lo rende affidabile: la schermata principale, l'unica azione significativa, i dati che la sostengono e il feedback che dice all'utente che ha funzionato. Tutto il resto è un candidato per dopo, non un requisito silenzioso per il lancio." },
    { type: "h3", text: "3. Definisce la prova successiva", id: "define-the-proof" }, { type: "p", text: "“Lanciare e vedere cosa succede” non è un piano di apprendimento. Decidi cosa ti aspetti di osservare nelle prime settimane: un flusso completato, un'azione ripetuta, una conversione a pagamento o un'intervista condotta dal fondatore con uno specifico tipo di utente. La misura non deve essere sofisticata; deve essere abbastanza vicina al comportamento dell'utente da poter cambiare la prossima decisione di prodotto." },
    { type: "h2", text: "Cosa annotare prima di una schermata", id: "before-a-screen" }, { type: "ul", items: ["Il primo utente: un ruolo, una situazione e un espediente doloroso", "Il ciclo fondamentale: la più piccola azione che crea valore e può ripetersi", "Il confine di lancio: ciò che è esplicitamente fuori ambito per la versione uno", "Il requisito di fiducia: ciò che l'utente deve vedere, controllare o capire prima di agire", "Il prossimo punto di prova: il comportamento o la conversazione che merita un altro ciclo di sviluppo"] },
    { type: "h2", text: "Il test dell'ambito che usiamo", id: "scope-test" }, { type: "p", text: "Prendi ogni funzionalità proposta e fai una domanda: rende più probabile il successo del ciclo fondamentale per il primo utente? Se la risposta è no, spostala fuori dalla prima release. Se è forse, annota l'ipotesi che sta proteggendo e trova un modo più economico per testarla. Questo impedisce a una funzionalità utile di diventare una scusa permanente per ritardare il prodotto." },
    { type: "quote", text: "Lo scopo di un brief non è raccogliere tutto ciò che potresti costruire. È rendere evidente la prossima decisione di sviluppo.", cite: "una regola che usiamo negli avvii di prodotto" },
    { type: "callout", title: "Come lo usiamo in Start Apps Studio", text: "Prima di quotare una realizzazione, trasformiamo l'idea del fondatore in un ambito di una pagina: un utente, un ciclo fondamentale, le schermate e l'infrastruttura che lo supportano e l'evidenza che dovrebbe cambiare la decisione successiva. Il documento diventa il passaggio di consegne tra strategia, design, ingegneria e lancio, e il punto di riferimento quando una nuova funzionalità cerca di intrufolarsi nella versione uno." },
    { type: "h2", text: "Domande frequenti", id: "faq" }, { type: "faq", items: [{ q: "Quanto deve essere lungo un brief MVP?", a: "Abbastanza breve da leggerlo in una sola seduta e abbastanza specifico da prendere decisioni tra alternative. Una o due pagine sono di solito sufficienti quando identifica primo utente, ciclo fondamentale, confine di lancio, requisiti di fiducia e prossimo punto di prova." }, { q: "Il brief deve includere un elenco completo delle funzionalità?", a: "Includi le funzionalità che fanno funzionare il ciclo fondamentale, poi tieni il resto in una sezione di idee successive. Un parcheggio separato protegge le buone idee senza lasciare che diventino silenziosamente requisiti di lancio." }, { q: "E se l'utente target è ancora incerto?", a: "Annota i due candidati più forti e l'evidenza che li distinguerebbe. L'incertezza è utile quando è esplicita; diventa costosa quando è nascosta dentro un ampio ambito di prodotto." }, { q: "Il brief deve essere finito prima che inizi il design?", a: "Dovrebbe essere abbastanza chiaro da guidare il primo passaggio di design, non congelato per sempre. Il design può far emergere una domanda migliore, ma ogni cambiamento dovrebbe aggiornare l'ambito e la prova che stai cercando di raccogliere." }] },
  ] },
  translatedPosts: IT_TRANSLATED_POSTS,
};

export default IT_EDITORIAL_CONTENT;