import { getPost } from "../posts";
import type { LocaleEditorialContent } from "../editorial";
import { TR_TRANSLATED_POSTS } from "./tr-posts";

const sourcePost = getPost("the-mvp-brief-is-your-first-product-decision");
if (!sourcePost) throw new Error("MVP source post is missing.");

export const TR_EDITORIAL_CONTENT: LocaleEditorialContent = {
  copy: { journalName: "The Journal · Cilt I", journalTitle: "Stüdyodan saha notları.", journalDescription: "Google'da sıralanan ve yapay zekâ tarafından alıntılanan MVP'leri yayına alma notları: GEO, vibe-coding ve işte yapay zekânın durumu.", resourcesTitle: "Önce doğru şeyi, sonra da iyi olanı inşa edin.", resourcesDescription: "Ürün stratejisi, yapay zekâ destekli teslimat, teknoloji seçimleri, sahiplik, devir ve MVP'yi yayına alma üzerine pratik kaynaklar.", read: "Notu oku", minutes: "dk. okuma", allNotes: "Tüm notlar", sources: "Kaynaklar", shortAnswer: "Kısa yanıt", language: "Dil", translatedArticleTitle: "MVP özeti ilk ürün kararınızdır", translatedArticleDescription: "İşe yarayan bir MVP özeti ilk kullanıcıyı tanımlar, birinci sürümün sınırını çizer ve sonraki kararın kanıtını belirler." },
  resources: {
    title: "Önce doğru şeyi, sonra da iyi olanı inşa edin.", description: "Ürün stratejisi, yapay zekâ destekli teslimat, teknoloji seçimleri, sahiplik, devir ve MVP'yi yayına alma üzerine pratik kaynaklar.", eyebrow: "Start Apps Studio · Kaynaklar", primaryAction: "Projenizi konuşalım", journalAction: "Journal'ı oku",
    routes: { title: "Sonraki rotayı seçin", intro: "Doğru ilk kilometre taşı, ne kadar yazılım hayal edebildiğinize değil, neyi kanıtlamanız gerektiğine bağlıdır.", cards: [
      { kicker: "01 · Yön", title: "En küçük faydalı kanıtla başlayın", text: "Bir lansman sitesi insanların teklifi anlayıp anlamadığını yanıtlar. Bir prototip deneyime tepki verip veremeyeceklerini yanıtlar. Bir MVP ise gerçek kullanıcıların ne yaptığını yanıtlar.", bullets: ["Sonraki sürümün açması gereken tek kararı seçin", "İlk sürümü ondan öğrenebileceğiniz kadar dar tutun", "İhtiyacınız olan kanıta uyan paketi kullanın"] },
      { kicker: "02 · Yapay zekâ destekli teslimat", title: "Yapı sağlam olduğunda hız faydalıdır", text: "Yapay zekâ keşfi, kodlamayı ve incelemeyi hızlandırabilir. Ürün muhakemesinin, mimarinin, testin veya sonuçtan sorumlu kişinin yerini almaz.", bullets: ["Seçenekleri keşfetmek ve tekrarı azaltmak için yapay zekâyı kullanın", "Üretilen kodu gerçek kullanıcı akışlarına göre inceleyin", "Yayına alınan sistemi anlaşılır ve genişletilebilir tutun"] },
      { kicker: "03 · Sahiplik", title: "Devirde ne teslim edildiğini sorun", text: "Başarılı bir geliştirme, son sunumdan daha fazlasıdır. Kaynak kodu, tasarım dosyaları, hesaplar, dağıtım erişimi ve bağlam sizin veya sonraki ekibiniz için hazır olmalıdır.", bullets: ["Hesapların ve çalışma dosyalarının sahibini teyit edin", "Son haftadan önce çalışan ilerlemeyi gözden geçirin", "Belgelenmiş, sürdürülebilir bir temel ile ayrılın"] },
      { kicker: "04 · İş ortağı uyumu", title: "Çalışma biçimini karşılaştırın", text: "Bir ürün ortağı seçmeden önce kapsam netliğini, geri bildirim döngülerini, sorumluluğu, lansman sonrası desteği ve rotanın işinizin aşamasına uyup uymadığını karşılaştırın.", bullets: ["Ürün kararlarını kim veriyor?", "Ne zaman gerçek bir şey göreceksiniz?", "Başka bir ekip baştan başlamadan devam edebilir mi?"] },
    ] },
    packages: { title: "Paket rota rehberi", intro: "Herkese açık paketleri konuşma için başlangıç noktası olarak kullanın. Kapsam, çalışma başlamadan önce kararlaştırılır.", columns: ["Rota", "Yatırım", "Tipik süre", "Şuna ihtiyacınız olduğunda en iyisi"], rows: [
      { route: "Lansman Sitesi", investment: "$2,600", timing: "3–5 iş günü", bestFor: "Teklifi açıklamak ve güvenilir bir dijital varlık oluşturmak" }, { route: "Prototip", investment: "$6,000", timing: "5–10 gün", bestFor: "Bir fikri doğrulama, fon toplama veya ilk görüşmeler için somutlaştırmak" }, { route: "MVP", investment: "$15,000–$30,000", timing: "3–8 hafta", bestFor: "Gerçek bir web, iOS veya Android ürününü kullanıcıların eline vermek" }, { route: "Özel", investment: "$25,000", timing: "1–6 ay", bestFor: "Uzun vadeli sorumlulukla daha büyük veya karmaşık bir sistem inşa etmek" },
    ] },
    toolkit: { title: "İşin arkasındaki araç seti", intro: "Araçlar; ürün sonucu, devralacak ekip ve işin aşaması için seçilir.", groups: [
      { label: "Fikriniz görünür hâlde", description: "Bir kavramın dokunabileceğiniz, yatırımcılarla paylaşabileceğiniz ve gerçek kullanıcılarla test edebileceğiniz ekranlara nasıl dönüştüğü.", tools: [{ name: "Figma", note: "koddan önce tasarlanan her ekran", tone: "figma" }, { name: "Rork", note: "günler içinde gerçek telefonda deneyin", tone: "rork" }, { name: "Lovable", note: "günler içinde yayında lansman sitesi", tone: "lovable" }, { name: "Replit", note: "çalıştırıp düzenleyebileceğiniz çalışan ürün", tone: "replit" }] },
      { label: "Ürününüz kalıcı olacak şekilde inşa edildi", description: "Kullanıcılarınızın yüklediği, açtığı ve ödeme yaptığı uygulamayı çalıştıran mühendislik.", tools: [{ name: "React Native", note: "tek kod tabanı, iOS + Android", tone: "expo" }, { name: "Swift", note: "yerel iOS, iPhone'da en hızlı", tone: "swift" }, { name: "Kotlin", note: "yerel Android, Play Store'a tam erişim", tone: "kotlin" }, { name: "Node + PostgreSQL", note: "verileriniz güvenli, dışa aktarması size ait", tone: "node" }] },
      { label: "Gelir ve lansman, ilk günden", description: "Ödemeler, güncellemeler ve kod güvenliği sonradan eklenmez; baştan kurulur.", open: true, tools: [{ name: "Stripe", note: "tek seferlik, abonelikler, yükseltmeler", tone: "stripe" }, { name: "RevenueCat", note: "App Store ve Play Store faturalaması", tone: "revenuecat" }, { name: "GitHub", note: "günlük yedekler: kodunuz hep güvende", tone: "github" }, { name: "Automation", note: "n8n + Make angaryayı halleder", tone: "hooks" }] },
      { label: "Arka planda yapay zekâ, yolunuzda değil", description: "Bir kişi yönün ve kalite çıtasının sahibi olurken yapay zekâ araştırmayı, uygulamayı ve incelemeyi destekleyebilir.", tools: [{ name: "Claude", note: "ana geliştirici ve kod inceleyicisi", tone: "claude" }, { name: "Gemini", note: "tüm ürünü tek seferde inceler", tone: "gemini" }, { name: "GPT-5", note: "metinler, akışlar ve yaratıcı yön", tone: "gpt" }, { name: "Llama 4", note: "hassas işler için kendi sunucunuzda seçenek", tone: "llama" }] },
    ], footnote: "Kodu, hesapları ve çalışma dosyalarını siz tutarsınız. Daha iyi bir araç çıktığında, ürününüzü rehin tutmadan değiştirilebilir." },
    journal: { title: "Journal'dan saha notları", text: "MVP stratejisi, SEO, GEO, vibe-coded uygulamalar ve ürünü yayına almayı kolaylaştıran kararlar üzerine daha uzun notlar.", readAction: "Notu oku", minutesLabel: "dk. okuma", allAction: "Tüm Journal notları", fallbackCategory: "Journal", postSlugs: ["base44-vs-lovable-which-one-for-your-next-app", "the-mvp-brief-is-your-first-product-decision", "make-your-brand-visible-in-chatgpt", "vibe-coded-apps-have-an-seo-problem", "backlinks-still-decide-who-gets-recommended", "ai-overviews-citation-playbook-for-mvps"] },
    cta: { title: "Aklınızda bir rota var mı?", text: "Nerede olduğunuzu, neyi kanıtlamanız gerektiğini ve şu anda neyin takıldığını paylaşın.", action: "Net bir sonraki adımı alın" },
  },
  post: { slug: sourcePost.slug, publishedAt: sourcePost.publishedAt, readMinutes: sourcePost.readMinutes, title: "MVP özeti ilk ürün kararınızdır", seoTitle: "MVP Özetleri: İlk Ürün Kararınız | Start Apps Studio", description: "İşe yarayan bir MVP özeti bir fikri tanımlamaktan fazlasını yapar. Kullanıcıyı tanımlar, birinci sürümün etrafına kesin bir sınır çizer ve geliştirmeye devam edip etmeyeceğinizi söyleyen kanıtı belirler.", seoDescription: "MVP özetiniz evrak işi değil, bir ürün kararıdır. Tasarım veya kod başlamadan önce faydalı bir özetin tanımlaması gereken üç şeyi öğrenin.", excerpt: "En iyi MVP özetleri uzun değildir. Ürünün kimin için olduğuna, birinci sürümün neyi yapmayı reddettiğine ve hangi kanıtın sonraki çalışma haftasını hak ettiğine karar verir.", category: "Saha Notları", tags: ["MVP", "Ürün stratejisi", "Kurucular", "Kapsam"], body: [
    { type: "answer", text: "İşe yarayan bir MVP özeti tasarım başlamadan önce üç karar verir: ürünün kimin için olduğu, birinci sürümün bilinçli olarak neleri dışarıda bırakacağı ve hangi kullanıcı kanıtının sonraki yatırımı haklı çıkaracağı. Bu yüzden özet evrak işi değildir. İlk ürün kararıdır." },
    { type: "p", text: "Kurucular çoğu zaman aslında fikrin açıklaması olan bir özetle gelir: pazar hakkında birkaç paragraf, bir özellik listesi ve ürünün bir gün nereye gidebileceğine dair bir cümle. Sohbet başlatmaya yeter, ancak üzerine ürün çıkarmaya yetmez. Bir geliştirme ekibinin, hedefi test edilebilir seçimler dizisine dönüştüren daha küçük ve daha keskin bir belgeye ihtiyacı vardır." },
    { type: "h2", text: "İşe yarayan bir özet üç iş görür", id: "three-jobs" }, { type: "h3", text: "1. Sorunu olan kişiyi tanımlar", id: "name-the-user" },
    { type: "p", text: "“Küçük işletmeler” bir pazardır; ilk kullanıcı değildir. İyi bir özet kişiyi, içinde bulunduğu anı ve bugün kullandığı geçici çözümü tanımlar. Yarınki iptalleri doldurmaya çalışan bir klinik yöneticisinin sorunu, ikisi de sağlık sektöründe olsa bile yeni randevu arayan bir hastanın sorunundan farklıdır. İlk kullanıcı ne kadar özgülse, ürünün sonra ne yapması gerektiğine karar vermek o kadar kolaylaşır." },
    { type: "h3", text: "2. Birinci sürümün çevresine bir çizgi çeker", id: "draw-the-line" }, { type: "p", text: "Özellik listesi size hayal edileni söyler. Kapsam çizgisi ise neyin inşa edileceğini söyler. Temel döngüyü tek cümleyle yazın; ardından o döngüyü güvenilir kılan işleri sıralayın: ana ekran, tek anlamlı eylem, arkasındaki veriler ve kullanıcıya çalıştığını söyleyen geri bildirim. Geri kalan her şey daha sonrası için adaydır; lansman için sessiz bir gereklilik değildir." },
    { type: "h3", text: "3. Sonraki kanıtı tanımlar", id: "define-the-proof" }, { type: "p", text: "“Yayına alıp ne olduğuna bakmak” bir öğrenme planı değildir. İlk birkaç haftada ne gözlemlemeyi beklediğinize karar verin: tamamlanmış bir iş akışı, tekrar eden bir eylem, ücretli dönüşüm veya belirli bir kullanıcı türüyle kurucunun yaptığı görüşme. Ölçütün karmaşık olması gerekmez. Bir sonraki ürün kararını değiştirebilmesi için kullanıcının davranışına yeterince yakın olması gerekir." },
    { type: "h2", text: "Bir ekran öncesinde ne yazılmalı", id: "before-a-screen" }, { type: "ul", items: ["İlk kullanıcı: tek rol, tek durum ve can yakan tek geçici çözüm", "Temel döngü: değer yaratan ve tekrar tekrar gerçekleşebilen en küçük eylem", "Lansman sınırı: birinci sürüm için açıkça kapsam dışı olanlar", "Güven gereksinimi: kullanıcının harekete geçmeden önce görmesi, kontrol etmesi veya anlaması gerekenler", "Sonraki kanıt noktası: başka bir geliştirme turunu hak eden davranış veya konuşma"] },
    { type: "h2", text: "Kullandığımız kapsam testi", id: "scope-test" }, { type: "p", text: "Önerilen her özelliği ele alın ve tek soru sorun: Bu, temel döngünün ilk kullanıcı için başarılı olma olasılığını artırıyor mu? Yanıt hayırsa onu ilk sürümden çıkarın. Yanıt belkiyse, koruduğu varsayımı yazın ve o varsayımı test etmenin daha ucuz yolunu bulun. Bu, faydalı bir özelliğin ürünü geciktirmek için kalıcı bir mazerete dönüşmesini engeller." },
    { type: "quote", text: "Bir özetin amacı, inşa edebileceğiniz her şeyi kaydetmek değildir. Sonraki geliştirme kararını açık kılmaktır.", cite: "ürün başlangıçlarında kullandığımız bir kural" },
    { type: "callout", title: "Bunu Start Apps Studio'da nasıl kullanıyoruz", text: "Bir geliştirme için fiyat vermeden önce kurucunun fikrini tek sayfalık kapsama dönüştürürüz: bir kullanıcı, bir temel döngü, onu destekleyen ekranlar ve altyapı ve sonraki kararı değiştirmesi gereken kanıt. Belge; strateji, tasarım, mühendislik ve lansman arasındaki devir olur ve yeni bir özellik birinci sürüme sızmak istediğinde başvuru noktasıdır." },
    { type: "h2", text: "Sık sorulan sorular", id: "faq" }, { type: "faq", items: [{ q: "MVP özeti ne kadar uzun olmalı?", a: "Tek oturuşta okunacak kadar kısa, ödünleşimleri belirleyecek kadar özgül olmalıdır. İlk kullanıcıyı, temel döngüyü, lansman sınırını, güven gereksinimlerini ve sonraki kanıt noktasını tanımladığında bir ila iki sayfa genellikle yeterlidir." }, { q: "Özette tam bir özellik listesi olmalı mı?", a: "Temel döngünün işlemesini sağlayan özellikleri ekleyin; kalanını sonraki fikirler bölümünde tutun. Ayrı bir bekleme listesi, iyi fikirleri sessizce lansman gereksinimine dönüşmelerine izin vermeden korur." }, { q: "Hedef kullanıcı hâlâ belirsizse ne olur?", a: "En güçlü iki adayı ve onları ayıracak kanıtı yazın. Belirsizlik açık olduğunda faydalıdır; geniş bir ürün kapsamının içinde saklandığında pahalılaşır." }, { q: "Tasarım başlamadan önce özet bitmiş olmalı mı?", a: "İlk tasarım turuna yön verecek kadar net olmalı, sonsuza dek donmuş olmamalıdır. Tasarım daha iyi bir soruyu ortaya çıkarabilir; ancak her değişiklik kapsamı ve toplamaya çalıştığınız kanıtı güncellemelidir." }] },
  ] },
  translatedPosts: TR_TRANSLATED_POSTS,
};

export default TR_EDITORIAL_CONTENT;